### ISSUE TITLE
Document parameterized container names

### ISSUE THREAD

**Issue by zostay** [stevan/BreadBoard#32]
Is it intended that parameterized containers rename themselves to include all the parameter names? For example, given this snippet:

    my $pc = container X => [ qw( Y Z ) ] => as { ... }

I would expect the following test to pass:

    use Test::More;
    my $c = $pc->create( Y => $yc, Z => $zc );
    is($c->name, 'X', 'container is named X');

However, the passing test is actually:

    is($c->name, 'X|Y|Z', 'container is named X with parameters');

This means to recover the expected name, I have to call the `name` setter to adjust the container. This isn't a problem, I just wanted to know if this is the intended behavior and can provide a documentation patch to Bread::Board::Manual::Concepts::Advanced.

**Comment by yanick** [comment]
The doc patch has already been merged to master.
