### ISSUE TITLE
SetterInjection has hard-coded constructor name

### ISSUE THREAD

**Issue by dakkar** [stevan/BreadBoard#43]
`ConstructorInjection` uses the MOP (plus override) to find the constructor to call, but `SetterInjection` always calls `new`. Should I factor out the `constructor_name` attribute and use it in both injections?

**Comment by stevan** [comment]
Looks sensible to me, however I don't think anyone ever used SetterInjection. It is more annoying then it is worth and BlockInjection is a far more readable/understandable way to accomplish the same thing and have your actual intent be clearer.

**Comment by yanick** [comment]
Merged in. Thanks! :-)
