### ISSUE TITLE
CPAN Pull Request Challenge - June 2015

### ISSUE THREAD

**Issue by kaoru** [stevan/BreadBoard#46]
Hi there,

This month I got BreadBoard as my CPAN Pull Request Challenge. I know you already know about it because I already did a CPAN PR Challenge for one of your distributions in January :-)

It looks like there's a couple of issues and pull requests open on Github. Any in particular that you'd like me to take a look at?

Alex

**Comment by yanick** [comment]
@kaoru Hi! Long time no see. :-)

I just created #47, which might be easy for a BB beginner. You can also peruse the codebase and see if anything jumps at you.

**Comment by kaoru** [comment]
Excellent :-)
