### ISSUE TITLE
Dist::Zilla dependency issues - Dist::Zilla::Plugin::Test::ReportPrereqs

### ISSUE THREAD

**Issue by kaoru** [stevan/BreadBoard#48]
I managed to successfully run `dzil authordeps --missing | cpanm` on my Perl 5.18.4 perlbrew and somehow got into a weird state.

```
$ dzil authordeps --missing
[... no output ...]
```

But then...

```
$ dzil listdeps             
Required plugin Dist::Zilla::Plugin::Test::ReportPrereqs isn't installed.

Run 'dzil authordeps' to see a list of all required plugins.
You can pipe the list to your CPAN client to install or update them:

    dzil authordeps --missing | cpanm
```

Any ideas what's up with that?

On top of that, if I do install Dist::Zilla::Plugin::Test::ReportPrereqs manually things don't get any better.

```
$ cpanm Dist::Zilla::Plugin::Test::ReportPrereqs
[...]
1 distribution installed
```

But then...

```
$ dzil listdeps                                 
fatal: ambiguous argument 'releases...master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]' at /home/alex/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/Dist/Zilla/Plugin/ChangeStats/Git.pm line 61.
```

Any ideas? If I can't get the dependencies installed and dzil running then working on #47 is going to be tricky.

Thanks,

Alex

**Comment by kaoru** [comment]
Same issue on Perl 5.16.3, except that listdeps just says:

    $ dzil listdeps --missing 
    Can't locate Dist/Zilla/Plugin/Test/ReportPrereqs.pm in @INC (@INC contains: /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/x86_64-linux /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3 /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/x86_64-linux /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3 .) at /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Module/Runtime.pm line 317, <GEN1> line 13. at /home/alex/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Config/MVP/Assembler.pm line 87.

Instead of the nicer message because I was still on Dist::Zilla 5.016 on my Perl 5.16.3 brew.

**Comment by yanick** [comment]
You're almost there. Just create a local branch 'releases' off origin/releases, and you should be good

**Comment by autarch** [comment]
This isn't a problem with Bread::Board, it's a problem with Yanick's bundle. See https://github.com/yanick/Dist-Zilla-PluginBundle-YANICK/issues/6 for details.

**Comment by yanick** [comment]
The creation of the 'releases' branch should have resolved the issue. Closing.
