### ISSUE TITLE
#53 breaks backwards-compat

### ISSUE THREAD

**Issue by grazzini** [stevan/BreadBoard#64]
We have a number of modules that extend the Bread::Board DSL by doing:

```
    Moose::Exporter->setup_import_methods(
        ...
        also  => 'Bread::Board',
    );
```

If there's not a compelling reason for #53, can you please revert it?

Thanks!

**Comment by yanick** [comment]
Yeah, I'll try to revert it in the next few days. I'm not exactly in love how Moose::Exporter makes other package care about how BB exports its functions, but that's not really your problem. :-)

**Comment by grazzini** [comment]
Great - thanks!

**Comment by yanick** [comment]
Done and on its way to cpan.
